---
- name: 'Add Argo chart repository.'
  kubernetes.core.helm_repository:
    name: 'argo'
    repo_url: 'https://argoproj.github.io/argo-helm'

- name: 'Deploy Argo CD.'
  kubernetes.core.helm:
    name: 'argocd'
    chart_ref: 'argo/argo-cd'
    release_namespace: 'argocd'
    create_namespace: yes
    values:
      secret:
        createSecret: yes
        argocdServerAdminPassword: "{{ password | password_hash('bcrypt') }}"
      server:
        service:
          type: 'ClusterIP'
        extraArgs:
          - '--insecure'

- name: 'Argo CD Server ingress.'
  kubernetes.core.k8s:
    kubeconfig: '~/.kube/config'
    namespace: 'argocd'
    definition:
      apiVersion: 'networking.k8s.io/v1'
      kind: 'Ingress'
      metadata:
        name: 'argocd-server'
        annotations:
          kubernetes.io/ingress.class: 'traefik-cert-manager'
          cert-manager.io/cluster-issuer: 'letsencrypt'
      spec:
        rules:
          - host: "argocd.{{ route53_personal_fqdn }}"
            http:
              paths:
                - pathType: 'Prefix'
                  path: '/'
                  backend:
                    service:
                      name: 'argocd-server'
                      port:
                        number: 80
          - host: "argocd.{{ route53_private_fqdn }}"
            http:
              paths:
                - pathType: 'Prefix'
                  path: '/'
                  backend:
                    service:
                      name: 'argocd-server'
                      port:
                        number: 80
        tls:
          - hosts:
              - "argocd.{{ route53_personal_fqdn }}"
              - "*.argocd.{{ route53_personal_fqdn }}"
            secretName: "argocd.{{ route53_personal_fqdn }}-certificate"
          - hosts:
              - "argocd.{{ route53_private_fqdn }}"
              - "*.argocd.{{ route53_private_fqdn }}"
            secretName: "argocd.{{ route53_private_fqdn }}-certificate"

- name: 'Argo CD Server ingress route.'
  kubernetes.core.k8s:
    kubeconfig: '~/.kube/config'
    namespace: 'argocd'
    definition:
      apiVersion: 'traefik.containo.us/v1alpha1'
      kind: 'IngressRoute'
      metadata:
        name: 'argocd-server'
        namespace: 'argocd'
        annotations:
          kubernetes.io/ingress.class: 'traefik-cert-manager'
          cert-manager.io/cluster-issuer: 'letsencrypt'
      spec:
        entryPoints:
          - 'web'
          - 'websecure'
        routes:
          - kind: 'Rule'
            match: "Host(`argocdgrpc.{{ route53_personal_fqdn }}`, `argocdgrpc.{{ route53_private_fqdn }}`)"
            priority: 11
            services:
              - name: 'argocd-server'
                namespace: 'argocd'
                port: 80
                scheme: 'h2c'
