---
- name: 'Add Argo chart repository.'
  kubernetes.core.helm_repository:
    name: 'argo'
    repo_url: 'https://argoproj.github.io/argo-helm'

- name: 'Deploy Argo CD.'
  kubernetes.core.helm:
    name: 'argocd'
    chart_ref: 'argo/argo-cd'
    release_namespace: 'argocd'
    create_namespace: yes
    values:
      service:
        type: ClusterIP
      secret:
        createSecret: yes
        argocdServerAdminPassword: "{{ password | password_hash('bcrypt') }}"
      extraArgs:
        - '--insecure'

- name: 'Argo CD Server ingress.'
  kubernetes.core.k8s:
    kubeconfig: '~/.kube/config'
    namespace: 'argocd'
    definition:
      apiVersion: traefik.containo.us/v1alpha1
      kind: IngressRoute
      metadata:
        name: argocd-server
        namespace: argocd
      spec:
        entryPoints:
          - web
          - websecure
        routes:
          - kind: Rule
            match: Host(`argocd.{{ route53_personal_fqdn }}`, `argocd.{{ route53_private_fqdn }}`)
            priority: 10
            services:
              - name: argocd-server
                port: 80
          - kind: Rule
            match: Host(`argocd.{{ route53_personal_fqdn }}`, `argocd.{{ route53_private_fqdn }}`) && Headers(`Content-Type`, `application/grpc`)
            priority: 11
            services:
              - name: argocd-server
                port: 80
                scheme: h2c
        tls:
          certResolver: "{{ route53_private_domain_basename }}"
          domains:
            - main: "argocd.{{ route53_personal_fqdn }}"
              sans:
              - "*.argocd.{{ route53_personal_fqdn }}"
            - main: "argocd.{{ route53_private_fqdn }}"
              sans:
              - "*.argocd.{{ route53_private_fqdn }}"
