---
- name: 'Create or update SSM policy for cluster.'
  community.aws.iam_policy:
    aws_access_key: "{{ aws.profiles.default.key_id }}"
    aws_secret_key: "{{ aws.profiles.default.secret_key }}"
    iam_type: 'user'
    iam_name: "k8s_{{ k8s_cluster }}"
    policy_name: "k8s_{{ k8s_cluster }}_policy"
    state: 'present'
    skip_duplicates: no
    policy_json: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
              "ssm:GetParameterHistory",
              "ssm:GetParametersByPath",
              "ssm:GetParameters",
              "ssm:GetParameter",
              "ssm:PutParameter"
            ],
            "Resource": "arn:aws:ssm:*:{{ aws.defaults.account_id }}:parameter/{{ k8s_cluster }}*"
          }
        ]
      }
