---
- name: 'Add External-Secrets chart repository.'
  kubernetes.core.helm_repository:
    name: 'external-secrets'
    repo_url: 'https://external-secrets.github.io/kubernetes-external-secrets/'

- name: 'Deploy External-Secrets.'
  kubernetes.core.helm:
    name: 'external-secrets'
    chart_ref: 'external-secrets/kubernetes-external-secrets'
    release_namespace: 'external-secrets'
    create_namespace: yes
    values:
      envVarsFromSecret.AWS_ACCESS_KEY_ID: "{{ aws.profiles['k8s_' + k8s_cluster].key_id }}"
      envVarsFromSecret.AWS_SECRET_ACCESS_KEY: "{{ aws.profiles['k8s_' + k8s_cluster].secret_key }}"
      env.POLLER_INTERVAL_MILLISECONDS: 3600000
      env.AWS_REGION: "{{ aws.defaults.region }}"
