---
- name: 'Add nfs-subdir-external-provisioner chart repository.'
  kubernetes.core.helm_repository:
    name: 'nfs-subdir-external-provisioner'
    repo_url: 'https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/'

- name: 'Deploy nfs-subdir-external-provisioner.'
  kubernetes.core.helm:
    name: 'nfs-subdir-external-provisioner'
    chart_ref: 'nfs-subdir-external-provisioner/nfs-subdir-external-provisioner'
    release_namespace: 'nfs-server'
    create_namespace: yes
    values:
      nfs:
        server: "{{ nfs_server_ip_address }}"
        path: "/{{ zfs_nfs_root }}/nfs/k8s_clusters/{{ k8s_cluster }}"
        volumeName: "nfs-root-{{ k8s_cluster }}"
      storageClass:
        create: yes
        provisionerName: "{{ k8s_cluster }}-nfs-provisioner"
        defaultClass: yes
        name: 'nfs-client'
        allowVolumeExpansion: yes
        reclaimPolicy: 'Delete'
        archiveOnDelete: yes
        accessModes: 'ReadWriteMany'
