---
- name: 'Add Traefik chart repository.'
  kubernetes.core.helm_repository:
    name: 'traefik'
    repo_url: 'https://helm.traefik.io/traefik'

- name: 'Deploy Traefik.'
  kubernetes.core.helm:
    name: 'traefik'
    chart_ref: 'traefik/traefik'
    release_namespace: 'traefik'
    create_namespace: yes
    values:
      ports:
        traefik:
          port: 9000
          hostPort: 9000
          expose: yes
          exposedPort: 9000
          protocol: 'TCP'
        web:
          port: 80
          expose: yes
          exposedPort: 80
          protocol: 'TCP'
          # hostPort: 80
          # nodePort: 32080
        websecure:
          port: 443
          expose: yes
          exposedPort: 443
          protocol: 'TCP'
          # hostPort: 443
          # nodePort: 32443
          tls:
            enabled: yes
            options: ""
      ingressRoute:
        dashboard:
          enabled: yes
      securityContext:
        capabilities:
          drop: ['ALL']
          add: ['NET_BIND_SERVICE']
        readOnlyRootFilesystem: yes
        runAsGroup: 0
        runAsNonRoot: no
        runAsUser: 0
      logs:
        general:
          level: ERROR
        access:
          enabled: yes
      hostNetwork: yes
      service:
        enabled: yes
        type: 'NodePort'
      providers:
        kubernetesCRD:
          enabled: yes
          allowCrossNamespace: yes
          namespaces:
            - 'default'
            - 'argocd'
            - 'traefik'
            - 'whoami'
        kubernetesIngress:
          enabled: yes
          namespaces:
            - 'default'
            - 'argocd'
            - 'traefik'
            - 'whoami'
          publishedService:
            enabled: yes
