---
- name: 'Add Traefik chart repository.'
  kubernetes.core.helm_repository:
    name: 'traefik'
    repo_url: 'https://helm.traefik.io/traefik'

- name: 'Deploy Traefik.'
  kubernetes.core.helm:
    name: 'traefik'
    chart_ref: 'traefik/traefik'
    release_namespace: 'traefik'
    create_namespace: yes
    values:
      ingressRoute:
        dashboard:
          enabled: yes
      providers:
        kubernetesCRD:
          enabled: yes
          allowCrossNamespace: yes
          namespaces:
            - 'default'
            - 'argocd'
            - 'traefik'
            - 'whoami'
        kubernetesIngress:
          enabled: yes
          namespaces:
            - 'default'
            - 'argocd'
            - 'traefik'
            - 'whoami'
          publishedService:
            enabled: yes
      logs:
        general:
          level: ERROR
        access:
          enabled: yes
      ports:
        traefik:
          port: 9000
          hostPort: 9000
          expose: yes
          exposedPort: 9000
          protocol: TCP
        web:
          port: 8000
          expose: yes
          exposedPort: 80
          protocol: TCP
          nodePort: 32080
        websecure:
          port: 8443
          expose: yes
          exposedPort: 443
          protocol: TCP
          nodePort: 32443
          tls:
            enabled: no
      service:
        enabled: yes
        type: NodePort
