
description: |-
    Proxmox LXC Container - Currently Unused
prompt:
    colors:
        primary: 108
        secondary: 11
        tertiary: 160
    emoji: 🌅
pve_host_index: 3
pve_ip_address: 10.3.0.103
pve_mac_address: de:fe:c8:03:00:67
pve_vm_id: '103'
