
description: |-
    Proxmox LXC Container - Currently Unused
prompt:
    colors:
        primary: 184
        secondary: 124
        tertiary: 19
    emoji: ⛵
pve_host_index: 5
pve_ip_address: 10.1.0.105
pve_mac_address: de:fe:c8:01:00:69

pve_vm_id: '105'
