
description: |-
    Proxmox LXC Container - Currently Unused
prompt:
    colors:
        primary: 19
        secondary: 220
        tertiary: 100
    emoji: 🎻
pve_host_index: 5
pve_ip_address: 10.4.0.105
pve_mac_address: de:fe:c8:04:00:69

pve_vm_id: '105'
