
description: |-
    Proxmox LXC Container - Currently Unused
prompt:
    colors:
        primary: 28
        secondary: 230
        tertiary: 130
    emoji: 🦉
pve_host_index: 6
pve_ip_address: 10.2.0.106
pve_mac_address: de:fe:c8:02:00:6a

pve_vm_id: '106'
