description: |-
    Proxmox LXC Container - Kubernetes Node (Longtable)
prompt:
    colors:
        primary: 18
        secondary: 210
        tertiary: 61
    emoji: 👄
pve_host_index: 11
pve_ip_address: 10.3.0.111
pve_mac_address: de:fe:c8:03:00:6f
pve_vm_id: '111'
