
description: |-
    Proxmox LXC Container - Currently Unused
prompt:
    colors:
        primary: 208
        secondary: 173
        tertiary: 59
    emoji: ''
pve_host_index: 16
pve_ip_address: 10.3.0.116
pve_mac_address: de:fe:c8:03:00:74
pve_vm_id: '116'
