description: |-
    Proxmox LXC Container - Currently Unused
prompt:
    colors:
        primary: 95
        secondary: 22
        tertiary: 145
    emoji: ''
pve_host_index: 20
pve_ip_address: 10.1.0.120
pve_mac_address: de:fe:c8:01:00:78

pve_vm_id: '120'
