---
- name: 'Set some user/group facts...'
  ansible.builtin.include_role:
    name: 'ndouglas.deploy_dotfiles'
    tasks_from: 'set_dotfiles_user.yaml'

- name: 'Set some important facts...'
  ansible.builtin.set_fact:
    torrents_root_path: '/torrents'

- name: 'Set some basic facts...'
  ansible.builtin.include_role:
    name: 'ndouglas.deploy_dotfiles'
    tasks_from: 'set_common_facts.yaml'

- name: 'Set some useful facts.'
  ansible.builtin.set_fact:
    instance_storage_path: "{{ torrents_root_path }}/clients/{{ instance_id }}"
    instance_domain_path: "{{ torrents_root_path }}/domains/{{ instance_domain }}"
    instance_domain_data_path: "{{ torrents_root_path }}/data/{{ instance_domain }}"
    transmission_peer_port: "{{ base_port + ( instance_id | int ) }}"
    service_name: "{{ padded_instance_id }}{{ instance_domain }}"

- name: 'Set some more service facts.'
  ansible.builtin.set_fact:
    service_fqdn: "{{ service_name }}.{{ fqdns.private }}"
    domain_fqdn: "{{ instance_domain }}.{{ fqdns.private }}"

- name: 'Create instance root directory.'
  ansible.builtin.file:
    path: "{{ instance_storage_path }}"
    state: 'directory'
    mode: '0755'
    owner: "{{ user }}"
    group: "{{ group }}"

- name: 'Create symlink pointing to instance ID from domain.'
  ansible.builtin.file:
    path: "{{ instance_domain_path }}"
    src: "{{ instance_storage_path }}"
    state: 'link'

- name: 'Create domain secondary destination path.'
  ansible.builtin.file:
    path: "{{ instance_domain_data_path }}"
    state: 'directory'
    mode: '0755'
    owner: "{{ user }}"
    group: "{{ group }}"

- name: 'Prepare directory structure.'
  ansible.builtin.file:
    path: "{{ instance_storage_path }}/{{ item }}"
    state: 'directory'
    mode: '0755'
  loop:
    - "config"
    - "watch"
    - "incomplete"
    - "downloads"

- name: "Copy Transmission template files {{ role_path }}/files/config/ -> {{ instance_storage_path }}/config/."
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ instance_storage_path }}/config/{{ item | basename | splitext | first }}"
    mode: '0755'
  with_fileglob:
    - "{{ role_path }}/files/config/*.j2"

- name: 'Create the Docker container.'
  community.docker.docker_container:
    name: "{{ service_name }}"
    image: 'linuxserver/transmission'
    state: 'started'
    restart: yes
    volumes:
     - "{{ instance_storage_path }}/config:/config"
     - "{{ instance_storage_path }}/watch:/watch"
     - "{{ instance_storage_path }}/incomplete:/incomplete"
     - "{{ instance_storage_path }}/downloads:/downloads"
     - "{{ instance_domain_data_path }}:/downloads2"
    labels: "{{ service_name | transmission_traefik_labels(service_fqdn, domain_fqdn) }}"
    ports:
      - "{{ transmission_peer_port }}:{{ transmission_peer_port }}"
      - "{{ transmission_peer_port }}:{{ transmission_peer_port }}/udp"
    memory: '1G'
    env:
      PUID: "{{ uid }}"
      PGID: "{{ gid }}"
      TZ: "America/New_York"
    restart_policy: 'unless-stopped'
