---
- name: 'Set some user/group facts...'
  ansible.builtin.include_role:
    name: 'ndouglas.deploy_dotfiles'
    tasks_from: 'set_dotfiles_user.yaml'

- name: 'Set some important facts...'
  ansible.builtin.set_fact:
    torrents_root_path: '/torrents'

- name: 'Create the core directory structure.'
  ansible.builtin.file:
    path: "{{ torrents_root_path }}/{{ item }}"
    state: 'directory'
    mode: '0755'
  loop:
    - "watch"
    - "clients"
    - "domains"
    - "data"
    - "ids"
    - "padded_ids"

- name: 'Install the watch cronjob.'
  ansible.builtin.cron:
    name: 'watch-torrents'
    job: |
      /bin/bash -lc 'torrent_watch_torrents "{{ torrents_root_path }}/watch"' > /dev/null 2>&1

- name: 'Create the Traefik container.'
  community.general.docker_container:
    name: 'traefik'
    image: 'traefik:2.2'
    restart_policy: 'unless-stopped'
    recreate: yes
    ports:
      - '8080:8080'
      - '80:80'
      - '443:443'
    volumes:
      - "{{ ansible_env.HOME }}/traefik:/etc/traefik"
      - '/var/run/docker.sock:/var/run/docker.sock'
    command: |
      --api.dashboard=false
      --serversTransport.insecureskipverify=true
      --providers.docker=true
      --entryPoints.web
      --entryPoints.web.address=':80'
      --entryPoints.web.http
      --entryPoints.web.http.redirections
      --entryPoints.web.http.redirections.entryPoint
      --entryPoints.web.http.redirections.entryPoint.to='websecure'
      --entryPoints.web.http.redirections.entryPoint.scheme='https'
      --entryPoints.web.forwardedHeaders.insecure
      --entryPoints.websecure
      --entryPoints.websecure.address=':443'
      --certificatesResolvers.hellholt.acme.email="letsencrypt@tenesm.us"
      --certificatesResolvers.hellholt.acme.storage='/etc/traefik/letsencrypt.json'
      --certificatesResolvers.hellholt.acme.dnsChallenge
      --certificatesResolvers.hellholt.acme.dnsChallenge.provider='route53'
    env:
      AWS_ACCESS_KEY_ID: "{{ aws.profiles.route53.key_id }}"
      AWS_SECRET_ACCESS_KEY: "{{ aws.profiles.route53.secret_key }}"
      AWS_HOSTED_ZONE_ID: "{{ aws.profiles.route53.zone_ids.private }}"
    container_default_behavior: 'no_defaults'

- name: 'Create privately-resolvable Route 53 records for the host.'
  community.aws.route53:
    overwrite: yes
    aws_access_key: "{{ aws.profiles.route53.key_id }}"
    aws_secret_key: "{{ aws.profiles.route53.secret_key }}"
    hosted_zone_id: "{{ aws.profiles.route53.zone_ids.private }}"
    state: 'present'
    type: 'A'
    record: "{{ fqdns.private }}"
    value: "{{ ipv4_address }}"

- name: 'Create privately-resolvable Route 53 wildcard records for the host.'
  community.aws.route53:
    overwrite: yes
    aws_access_key: "{{ aws.profiles.route53.key_id }}"
    aws_secret_key: "{{ aws.profiles.route53.secret_key }}"
    hosted_zone_id: "{{ aws.profiles.route53.zone_ids.private }}"
    state: 'present'
    type: 'A'
    record: "*.{{ fqdns.private }}"
    value: "{{ ipv4_address }}"

- name: 'Create a WebDAV server to allow torrent uploads.'
  community.general.docker_container:
    name: 'webdav'
    image: 'ugeek/webdav:amd64-alpine'
    restart_policy: 'unless-stopped'
    recreate: yes
    volumes:
      - "/torrents/watch:/data"
    env:
      USERNAME: "{{ user }}"
      PASSWORD: "{{ password }}"
      UID: "{{ uid }}"
      GID: "{{ gid }}"
      TZ: "America/New_York"
    labels:
      'traefik.enable': 'true'
      'traefik.http.routers.webdav.entrypoints': "websecure"
      'traefik.http.routers.webdav.rule': "Host(`webdav.{{ fqdns.private }}`)"
      'traefik.http.routers.webdav.tls': 'true'
      'traefik.http.routers.webdav.tls.certresolver': 'hellholt'
      'traefik.http.routers.webdav.service': 'webdav'
      'traefik.http.services.webdav.loadbalancer.server.port': '80'
      'traefik.http.services.webdav.loadbalancer.server.scheme': 'http'
      'traefik.http.middlewares.securedheaders.headers.forcestsheader': 'true'
      'traefik.http.middlewares.securedheaders.headers.sslRedirect': 'true'
      'traefik.http.middlewares.securedheaders.headers.STSPreload': 'true'
      'traefik.http.middlewares.securedheaders.headers.ContentTypeNosniff': 'true'
      'traefik.http.middlewares.securedheaders.headers.BrowserXssFilter': 'true'
      'traefik.http.middlewares.securedheaders.headers.STSIncludeSubdomains': 'true'
      'traefik.http.middlewares.securedheaders.headers.stsSeconds': '63072000'
      'traefik.http.middlewares.securedheaders.headers.frameDeny': 'true'
      'traefik.http.middlewares.securedheaders.headers.browserXssFilter': 'true'
      'traefik.http.middlewares.securedheaders.headers.contentTypeNosniff': 'true'
    container_default_behavior: 'no_defaults'
