---
- name: 'Set some important facts...'
  ansible.builtin.set_fact:
    torrents_root_path: '/torrents'

- name: 'Create the core directory structure.'
  ansible.builtin.file:
    path: "{{ torrents_root_path }}/{{ item }}"
    state: 'directory'
    mode: '0755'
  loop:
    - "watch"
    - "clients"
    - "data"

- name: 'Install the watch cronjob.'
  ansible.builtin.cron:
    name: 'watch-torrents'
    job: |
      /bin/bash -lc 'torrents_watch_torrents "{{ torrents_root_path }}/watch"'
