#!/usr/bin/env bash
set -uo pipefail;
IFS=$'\n\t';

script_path="$(git rev-parse --show-toplevel)/git/hooks";
source "${script_path}/library.sh";

# Check Terraform format.
if terraform fmt -check -recursive; then
  dot_success_message "Terraform format check passed.";
else
  dot_failure_message "Terraform format check failed!";
  exit 1;
fi;

# Look for merge markers.
marker_found=0;
for this_file in $(git diff-index --diff-filter=ACM --cached --name-only HEAD --); do
  if egrep -rls "^<<<<<<< |^>>>>>>> $" "${this_file}" > /dev/null; then
    if ! dot_file_is_binary "${this_file}"; then
      dot_failure_message "Merge marker found in ${this_file}!";
      marker_found=$((marker_found+1));
    fi;
  fi;
done;
if [ "${marker_found}" -ne 0 ]; then
  exit "${marker_found}";
else
  dot_success_message "No merge markers found.";
fi;
