- name: 'Create the Argo CD Kubernetes namespace.'
  kubernetes.core.k8s:
    name: 'argocd'
    api_version: 'v1'
    kind: 'Namespace'
    state: 'present'
    kubeconfig: '~/.kube/config'

- name: 'Create temporary directory.'
  ansible.builtin.tempfile:
    state: 'directory'
  register: 'temporary_directory'
  changed_when: no

- name: 'Download Argo CD manifest.'
  ansible.builtin.get_url:
    url: 'https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml'
    dest: "{{ temporary_directory.path }}/argocd_install.yaml"
    owner: 'root'
    group: 'root'
    mode: '0440'
  changed_when: no

- name: 'Deploy Argo CD.'
  kubernetes.core.k8s:
    src: "{{ temporary_directory.path }}/argocd_install.yaml"
    state: 'present'
    kubeconfig: '~/.kube/config'
    namespace: 'argocd'
