- name: 'Add Traefik chart repository.'
  kubernetes.core.helm_repository:
    name: 'traefik'
    repo_url: 'https://helm.traefik.io/traefik'

- name: 'Deploy Traefik.'
  kubernetes.core.helm:
    name: 'traefik'
    chart_ref: 'traefik/traefik'
    release_namespace: 'traefik'
    create_namespace: yes
    values:
      additionalArguments:
        - --serversTransport.insecureskipverify=true
        - --entrypoints.websecure.http.tls.domains[0].main={{ k8s_cluster }}.{{ domains.private }}
        - --entrypoints.websecure.http.tls.domains[0].sans=*.{{ k8s_cluster }}.{{ domains.private }}
        - --certificatesResolvers.{{ domains.private | splitext | first }}.acme.dnsChallenge
        - --certificatesResolvers.{{ domains.private | splitext | first }}.acme.dnsChallenge.provider='route53'
        - --certificatesresolvers.cloudflare.acme.email=letsencrypt@{{ domains.private }}
        - --certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1
        - --certificatesresolvers.cloudflare.acme.storage=/certs/acme.json
      ingressRoute:
        dashboard:
          enabled: yes
      service:
        enabled: yes
        type: 'LoadBalancer'
        externalIPs:
          - "{{ ipv4_address }}"
