---
- name: 'Install K8s custom service.'
  remote_user: 'root'
  block:

    - name: 'Create K8s custom service.'
      ansible.builtin.copy:
        dest: '/etc/systemd/system/multi-user.target.wants/k8s-custom.service'
        content: |
          [Unit]
          Description=Kubernetes Custom Actions
          [Service]
          ExecStart=mount --make-rshared /
          [Install]
          WantedBy=multi-user.target

    - name: 'Start K8s custom service.'
      ansible.builtin.systemd:
        name: 'k8s-custom.service'
        daemon_reload: yes
        state: 'started'
        enabled: yes

- name: 'Install Kubernetes.'
  ansible.builtin.include_role:
    name: 'geerlingguy.kubernetes'
  vars:
    kubernetes_packages:
      - name: 'kubelet'
        state: 'present'
      - name: 'kubectl'
        state: 'present'
      - name: 'kubeadm'
        state: 'present'
      - name: 'kubernetes-cni'
        state: 'present'
    kubernetes_pod_network:
      cni: 'weave'
      cidr: '192.168.0.0/16'
    kubernetes_version: '1.20'
    kubernetes_role: "{{ k8s_role }}"
    kubernetes_ignore_preflight_errors: 'all'
    kubernetes_join_command_extra_opts: "--ignore-preflight-errors={{ kubernetes_ignore_preflight_errors }}"
    # kubernetes_config_init_configuration:
    kubernetes_config_cluster_configuration:
      clusterName: "{{ k8s_cluster }}"
      networking:
        podSubnet: "{{ kubernetes_pod_network.cidr }}"
      kubernetesVersion: "{{ kubernetes_version_kubeadm }}"
    kubernetes_config_kubelet_configuration:
      cgroupDriver: 'systemd'
