---
- name: 'Set facts as empty lists.'
  ansible.builtin.set_fact:
    hostnames: []
    zfs_paths: []
    ip_addresses: []

- name: 'Build some basic facts.'
  ansible.builtin.set_fact:
    zfs_paths: "{{ zfs_paths + [ '/' + zfs_nfs_root + '/nfs/k8s_clusters/' + hostvars[k8s_host_name].k8s_cluster ] }}"
  loop: "{{ groups['k8s'] }}"
  loop_control:
    index_var: 'index'
    loop_var: 'k8s_host_name'

- name: 'Build some basic facts.'
  ansible.builtin.set_fact:
    hostnames: "{{ hostnames + [ k8s_host_name ] }}"
    ip_addresses: "{{ ip_addresses + [ hostvars[k8s_host_name].pve_ip_address ] }}"
  loop: "{{ groups['k8s'] }}"
  loop_control:
    index_var: 'index'
    loop_var: 'k8s_host_name'

- name: 'Build list of NFS exports for Kubernetes clusters.'
  ansible.builtin.set_fact:
    nfs_exports: "{{ nfs_exports | default([]) + [ zfs_paths[index] + ' ' + ip_addresses[index] + '/32(' + nfs_mount_options + ')' ] }}"
  loop: "{{ groups['k8s'] }}"
  loop_control:
    index_var: 'index'
    loop_var: 'k8s_host_name'

- name: 'Ensure presence of relevant ZFS volumes for Kubernetes clusters.'
  become: yes
  community.general.zfs:
    name: "{{ zfs_nfs_root }}/nfs/k8s_clusters/{{ hostvars[k8s_host_name].k8s_cluster }}"
    state: 'present'
  loop: "{{ groups['k8s_masters'] }}"
  loop_control:
    index_var: 'index'
    loop_var: 'k8s_host_name'

- name: 'Export ZFS volumes for Kubernetes clusters.'
  become: yes
  ansible.builtin.blockinfile:
    path: '/etc/exports'
    block: "{{ nfs_exports | join('\n') }}"
  register: 'k8s_cluster_zfs_volumes'

- name: 'Export exports.'
  become: yes
  ansible.builtin.shell:
    cmd: 'exportfs -ra'
  when: 'k8s_cluster_zfs_volumes.changed'
