---
- name: 'Set facts as empty lists.'
  ansible.builtin.set_fact:
    hostnames: []
    zfs_paths: []
    ip_addresses: []

- name: 'Build some basic facts.'
  ansible.builtin.set_fact:
    hostnames: "{{ hostnames + [ pve_host_name ] }}"
    zfs_paths: "{{ zfs_paths + [ '/' + zfs_nfs_root + '/nfs/hosts/' + pve_host_name ] }}"
    ip_addresses: "{{ ip_addresses + [ hostvars[pve_host_name].pve_ip_address ] }}"
  loop: "{{ groups['pve_hosts'] }}"
  loop_control:
    index_var: 'index'
    loop_var: 'pve_host_name'

- name: 'Build list of NFS exports for Proxmox hosts.'
  ansible.builtin.set_fact:
    nfs_exports: "{{ nfs_exports | default([]) + [ zfs_paths[index] + ' ' + ip_addresses[index] + '/32(' + nfs_mount_options + ')' ] }}"
  loop: "{{ groups['pve_hosts'] }}"
  loop_control:
    index_var: 'index'
    loop_var: 'pve_host_name'

- name: 'Ensure presence of relevant ZFS volumes for Proxmox hosts.'
  become: yes
  community.general.zfs:
    name: "{{ zfs_nfs_root }}/nfs/hosts/{{ pve_host }}"
    state: 'present'
  loop: "{{ groups['pve_hosts'] }}"
  loop_control:
    index_var: 'index'
    loop_var: 'pve_host'

- name: 'Export ZFS volumes for Proxmox hosts.'
  become: yes
  ansible.builtin.blockinfile:
    path: '/etc/exports'
    block: "{{ nfs_exports | join('\n') }}"
  register: 'proxmox_host_zfs_volumes'

- name: 'Export exports.'
  become: yes
  ansible.builtin.shell:
    cmd: 'exportfs -ra'
  when: 'proxmox_host_zfs_volumes.changed'
