---
- name: 'Create privately-resolvable DNS records for the host.'
  delegate_to: 'localhost'
  community.aws.route53:
    overwrite: yes
    aws_access_key: "{{ route53_key_id }}"
    aws_secret_key: "{{ route53_secret_key }}"
    hosted_zone_id: "{{ route53_private_zone_id }}"
    state: 'present'
    type: 'A'
    record: "{{ route53_private_fqdn }}"
    value: "{{ route53_ipv4_address }}"

- name: 'Create privately-resolvable wildcard DNS records for the host.'
  delegate_to: 'localhost'
  community.aws.route53:
    alias: yes
    alias_hosted_zone_id: "{{ route53_private_zone_id }}"
    overwrite: yes
    aws_access_key: "{{ route53_key_id }}"
    aws_secret_key: "{{ route53_secret_key }}"
    hosted_zone_id: "{{ route53_private_zone_id }}"
    state: 'present'
    type: 'A'
    record: "*.{{ route53_private_fqdn }}"
    value: "{{ route53_private_fqdn }}"

- name: 'Create publicly-resolvable DNS records for the host.'
  delegate_to: 'localhost'
  community.aws.route53:
    alias: yes
    alias_hosted_zone_id: "{{ route53_personal_zone_id }}"
    overwrite: yes
    aws_access_key: "{{ route53_key_id }}"
    aws_secret_key: "{{ route53_secret_key }}"
    hosted_zone_id: "{{ route53_personal_zone_id }}"
    state: 'present'
    type: 'A'
    record: "{{ route53_personal_fqdn }}"
    value: "{{ route53_personal_domain }}"

- name: 'Create publicly-resolvable wildcard DNS records for the host.'
  delegate_to: 'localhost'
  community.aws.route53:
    alias: yes
    alias_hosted_zone_id: "{{ route53_personal_zone_id }}"
    overwrite: yes
    aws_access_key: "{{ route53_key_id }}"
    aws_secret_key: "{{ route53_secret_key }}"
    hosted_zone_id: "{{ route53_personal_zone_id }}"
    state: 'present'
    type: 'A'
    record: "*.{{ route53_personal_fqdn }}"
    value: "{{ route53_personal_fqdn }}"
