---
- name: 'Stop hosts.'
  ansible.builtin.include_role:
    name: 'ndouglas.proxmox'
    tasks_from: 'stop_host.yaml'
  ignore_errors: yes

- name: 'Destroy hosts.'
  ansible.builtin.include_role:
    name: 'ndouglas.proxmox'
    tasks_from: 'remove_host.yaml'
