- name: 'Reconfigure the application.'
  remote_user: 'root'
  block:

    - name: 'Preseed inithooks.'
      ansible.builtin.copy:
        dest: '/etc/inithooks.conf'
        content: |
          # Specific
          export ADMIN_PASS={{ password }}
          export ADMIN_EMAIL={{ host_email_address }}
          # Generic
          export ROOT_PASS={{ password }}
          export DB_PASS={{ password }}
          export APP_EMAIL={{ host_email_address }}
          export APP_PASS={{ password }}
          export SEC_ALERTS={{ host_email_address }}
          export SEC_UPDATES=FORCE
          export HUB_APIKEY={{ turnkey.api_key }}

    - name: 'Reinitialize the application.'
      ansible.builtin.command:
        cmd: |
          turnkey-init

- name: 'Add the backup job to cron.'
  remote_user: 'root'
  block:

    - name: 'Set the email address appropriately for cron jobs.'
      ansible.builtin.cron:
        name: MAILTO
        env: yes
        job: "{{ host_email_address }}"

    - name: 'Install the update cronjob.'
      ansible.builtin.cron:
        name: 'update-dotfiles'
        minute: "{{ 60 | random(seed=user_at_hostname) }}"
        job: |
          /bin/bash -lc 'tklbam-backup'

