---
- name: 'Create normal user account.'
  ansible.builtin.user:
    name: "{{ my.name.lower }}"
    password: "{{ password | password_hash('sha512', hostname) }}"
    shell: '/bin/bash'
    append: yes
    groups: 'sudo'
    create_home: yes
