---
- name: 'Create normal user account.'
  ansible.builtin.user:
    name: "{{ my.name.lower }}"
    shell: '/bin/bash'
    append: yes
    groups: 'sudo'
    create_home: yes

- name: 'Enable Passwordless Sudo'
  ansible.builtin.copy:
    content: "{{ my.name.lower }} ALL=(ALL:ALL) NOPASSWD:ALL"
    dest: "/etc/sudoers.d/{{ my.name.lower }}"
    mode: 0440
