---

- name: 'Set facts for the Filebot config path.'
  ansible.builtin.set_fact:
    filebot_config_dir: "{{ ansible_env.HOME }}/.filebot"

- name: "Create temporary directory."
  ansible.builtin.tempfile:
    state: 'directory'
  register: 'temporary_directory'
  changed_when: no

- name: "Copy Filebot template dotfiles {{ role_path }}/files/filebot/ -> temporary directory."
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ temporary_directory.path }}/{{ item | basename | splitext | first }}"
  with_fileglob:
    - "{{ role_path }}/files/filebot/*.j2"
  changed_when: no

- name: 'Delete the Filebot config directory.'
  ansible.builtin.file:
    path: "{{ filebot_config_dir }}"
    state: absent
  changed_when: no

- name: 'Create the Filebot config directory.'
  ansible.builtin.file:
    path: "{{ filebot_config_dir }}"
    owner: "{{ ndsc_user }}"
    group: "{{ ndsc_group }}"
    mode: '0700'
    state: directory
  changed_when: no

- name: "Copy Filebot dotfiles temporary directory -> {{ filebot_config_dir }}."
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ filebot_config_dir }}"
    owner: "{{ ndsc_user }}"
    group: "{{ ndsc_group }}"
    mode: '0600'
    force: yes
  with_fileglob:
    - "{{ temporary_directory.path }}/*"
  changed_when: no
