---
- name: 'Set facts for the AWS config file path.'
  ansible.builtin.set_fact:
    aws_config_dir: "{{ ansible_env.HOME }}/.aws"

- name: 'Delete the AWS config directory.'
  ansible.builtin.file:
    path: "{{ aws_config_dir }}"
    state: absent
  changed_when: no

- name: 'Create the AWS config directory.'
  ansible.builtin.file:
    path: "{{ aws_config_dir }}"
    owner: "{{ ndsc_user }}"
    group: "{{ ndsc_group }}"
    mode: '0700'
    state: directory
  changed_when: no

- name: "Copy AWS template dotfiles {{ role_path }}/files/aws/ -> {{ aws_config_dir }}"
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ aws_config_dir }}/{{ item | basename | splitext | first }}"
  with_fileglob:
    - "{{ role_path }}/files/aws/*.j2"
  changed_when: no
