---

###############################################################################
# A FACT-FINDING MISSION
###############################################################################

- name: 'Set dotfiles facts.'
  ansible.builtin.set_fact:
    bash_ordered_segments: 'options path env library ansible beets comics dotfiles ffmpeg hass host kasa proxmox r53 reddit torrents completion aliases'

- name: 'Set user and group.'
  ansible.builtin.include: 'set_dotfiles_user.yaml'
  when: 'user is not defined'

- name: 'Set dotfiles_home directory.'
  ansible.builtin.include: 'set_dotfiles_home_directory.yaml'
  when: 'dotfiles_home is not defined'

###############################################################################
# ALIASES
###############################################################################

- name: 'Copy Bash aliases dotfiles to destination.'
  block:

    - name: 'Copy Bash Aliases dotfiles to destination.'
      ansible.builtin.include: 'copy_bash_dotfiles.yaml'
      vars:
        id: 'aliases'
        source: "{{ role_path }}/files/bash/aliases"
        dest: "{{ dotfiles_home }}/.bash.aliases.d"

    - name: 'Set Mac-Specific Aliases'
      block:

        - name: 'Create aliases for various BSD tools to the GNU equivalents.'
          ansible.builtin.copy:
            dest: "{{ dotfiles_home }}/.bash.aliases.d/{{ item }}.sh"
            content: |
              #!/usr/bin/env bash

              # Detect if we have a g{{ item }}.
              if [ -x "$(command -v g{{ item }})" ]; then
                alias {{ item }}="g{{ item }}";
              fi
          loop:
            - 'date'
            - 'du'
            - 'echo'
            - 'sed'
            - 'stat'

        - name: 'Create alias for md5sum.'
          ansible.builtin.copy:
            dest: "{{ dotfiles_home }}/.bash.aliases.d/md5sum.sh"
            content: |
              #!/usr/bin/env bash

              alias md5sum="md5";

      when: 'host_is_mac'

###############################################################################
# ANSIBLE
###############################################################################

- name: 'Copy Bash Ansible dotfiles to destination.'
  ansible.builtin.include: 'copy_bash_dotfiles.yaml'
  vars:
    id: 'ansible'
    source: "{{ role_path }}/files/bash/ansible"
    dest: "{{ dotfiles_home }}/.bash.ansible.d"

###############################################################################
# BEETS
###############################################################################

- name: 'Copy Bash Beets dotfiles to destination.'
  block:

    - name: 'Copy Bash Beets dotfiles to destination.'
      ansible.builtin.include: 'copy_bash_dotfiles.yaml'
      vars:
        id: 'beets'
        source: "{{ role_path }}/files/bash/beets"
        dest: "{{ dotfiles_home }}/.bash.beets.d"

    - name: 'Set BEETSDIR environment variable.'
      ansible.builtin.copy:
        dest: "{{ dotfiles_home }}/.bash.env.d/beetsdir.sh"
        content: |
          #!/usr/bin/env bash

          export BEETSDIR="/volume1/Music/beets";

  when: "host_is_synology"

###############################################################################
# COMICS
###############################################################################

- name: 'Copy Bash Comics dotfiles to destination.'
  ansible.builtin.include: 'copy_bash_dotfiles.yaml'
  vars:
    id: 'comics'
    source: "{{ role_path }}/files/bash/comics"
    dest: "{{ dotfiles_home }}/.bash.comics.d"
  when: "host_is_synology and hostname == 'dayne'"

###############################################################################
# COMPLETION
###############################################################################

- name: 'Copy Bash Completion dotfiles to destination.'
  ansible.builtin.include: 'copy_bash_dotfiles.yaml'
  vars:
    id: 'completion'
    source: "{{ role_path }}/files/bash/completion"
    dest: "{{ dotfiles_home }}/.bash.completion.d"

###############################################################################
# DOTFILES
###############################################################################

- name: 'Copy Bash Dotfiles dotfiles to destination.'
  ansible.builtin.include: 'copy_bash_dotfiles.yaml'
  vars:
    id: 'dotfiles'
    source: "{{ role_path }}/files/bash/dotfiles"
    dest: "{{ dotfiles_home }}/.bash.dotfiles.d"

###############################################################################
# FFMPEG
###############################################################################

- name: 'Copy Bash FFMpeg dotfiles to destination.'
  ansible.builtin.include: 'copy_bash_dotfiles.yaml'
  vars:
    id: 'ffmpeg'
    source: "{{ role_path }}/files/bash/ffmpeg"
    dest: "{{ dotfiles_home }}/.bash.ffmpeg.d"

###############################################################################
# HOST
###############################################################################

- name: 'Check for existence of Host dotfiles source.'
  ansible.builtin.stat:
    path: "{{ role_path }}/files/bash/host/{{ hostname }}"
  register: host_dotfiles_path

- name: 'Copy Bash Host-specific dotfiles to destination.'
  ansible.builtin.include: 'copy_bash_dotfiles.yaml'
  vars:
    id: 'host'
    source: "{{ role_path }}/files/bash/host/{{ hostname }}"
    dest: "{{ dotfiles_home }}/.bash.host.d"
  when: 'host_dotfiles_path.stat.exists'

###############################################################################
# HOME ASSISTANT
###############################################################################

- name: 'Copy Bash Home Assistant dotfiles to destination.'
  ansible.builtin.include: 'copy_bash_dotfiles.yaml'
  vars:
    id: 'hass'
    source: "{{ role_path }}/files/bash/hass"
    dest: "{{ dotfiles_home }}/.bash.hass.d"

###############################################################################
# KASA
###############################################################################

- name: 'Copy Bash Kasa dotfiles to destination.'
  ansible.builtin.include: 'copy_bash_dotfiles.yaml'
  vars:
    id: 'kasa'
    source: "{{ role_path }}/files/bash/kasa"
    dest: "{{ dotfiles_home }}/.bash.kasa.d"

###############################################################################
# LIBRARY
###############################################################################

- name: 'Copy Bash Library dotfiles to destination.'
  ansible.builtin.include: 'copy_bash_dotfiles.yaml'
  vars:
    id: 'library'
    source: "{{ role_path }}/files/bash/library"
    dest: "{{ dotfiles_home }}/.bash.library.d"

###############################################################################
# ENVIRONMENT
###############################################################################

- name: 'Copy Bash Env dotfiles to destination.'
  ansible.builtin.include: 'copy_bash_dotfiles.yaml'
  vars:
    id: 'env'
    source: "{{ role_path }}/files/bash/env"
    dest: "{{ dotfiles_home }}/.bash.env.d"

###############################################################################
# OPTIONS
###############################################################################

- name: 'Copy Bash Options dotfiles to destination.'
  ansible.builtin.include: 'copy_bash_dotfiles.yaml'
  vars:
    id: 'options'
    source: "{{ role_path }}/files/bash/options"
    dest: "{{ dotfiles_home }}/.bash.options.d"

###############################################################################
# PATH
###############################################################################

- name: 'Copy Bash path dotfiles to destination.'
  block:

    - name: 'Copy Bash Path dotfiles to destination.'
      ansible.builtin.include: 'copy_bash_dotfiles.yaml'
      vars:
        id: 'path'
        source: "{{ role_path }}/files/bash/path"
        dest: "{{ dotfiles_home }}/.bash.path.d"

    - name: 'Syno-CLI Path Components'
      ansible.builtin.copy:
        dest: "{{ bash_path_path }}/syno-cli.sh"
        content: |
         #!/usr/bin/env bash

          # Syno-CLI provides nano, tput, etc.
          if [ -d "/volume1/@appstore/synocli-file/bin" ]; then
            PATH="${PATH}:/volume1/@appstore/synocli-file/bin";
          fi
      when: 'host_is_synology'

###############################################################################
# PROXMOX
###############################################################################

- name: 'Copy Bash Proxmox dotfiles to destination.'
  ansible.builtin.include: 'copy_bash_dotfiles.yaml'
  vars:
    id: 'proxmox'
    source: "{{ role_path }}/files/bash/proxmox"
    dest: "{{ dotfiles_home }}/.bash.proxmox.d"

###############################################################################
# RASPBERRY PI
###############################################################################

- name: 'Copy Bash Raspberry Pi dotfiles to destination.'
  ansible.builtin.include: 'copy_bash_dotfiles.yaml'
  vars:
    id: 'pi'
    source: "{{ role_path }}/files/bash/pi"
    dest: "{{ dotfiles_home }}/.bash.pi.d"
  when: 'host_is_raspbian'

###############################################################################
# REDDIT
###############################################################################

- name: 'Copy Bash Reddit dotfiles to destination.'
  ansible.builtin.include: 'copy_bash_dotfiles.yaml'
  vars:
    id: 'reddit'
    source: "{{ role_path }}/files/bash/reddit"
    dest: "{{ dotfiles_home }}/.bash.reddit.d"

###############################################################################
# ROUTE 53
###############################################################################

- name: 'Copy Bash Route 53 dotfiles to destination.'
  ansible.builtin.include: 'copy_bash_dotfiles.yaml'
  vars:
    id: 'r53'
    source: "{{ role_path }}/files/bash/r53"
    dest: "{{ dotfiles_home }}/.bash.r53.d"

###############################################################################
# TORRENTS
###############################################################################

- name: 'Copy Bash Torrent dotfiles to destination.'
  ansible.builtin.include: 'copy_bash_dotfiles.yaml'
  vars:
    id: 'torrents'
    source: "{{ role_path }}/files/bash/torrents"
    dest: "{{ dotfiles_home }}/.bash.torrents.d"

###############################################################################
# CORE
###############################################################################

- name: 'Copy Bash core dotfiles to destination.'
  ansible.builtin.template:
    backup: yes
    force: yes
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: '0755'
    src: "{{ item }}"
    dest: "{{ dotfiles_home }}/.{{ item | basename | regex_replace('^([^\\.]*).*', '\\1') }}"
  with_fileglob:
    - "{{ role_path }}/files/bash/core/*.sh.j2"
