---

###############################################################################
# A FACT-FINDING MISSION
###############################################################################

- name: 'Set some lists of Bash dotfile directories.'
  ansible.builtin.set_fact:
    bash_generic_items:
      - 'ansible'
      - 'dotfiles'
      - 'ffmpeg'
      - 'filebot'
      - 'hass'
      - 'k8s'
      - 'kasa'
      - 'proxmox'
      - 'r53'
      - 'reddit'
      - 'torrents'
    bash_special_items:
      - 'options'
      - 'path'
      - 'env'
      - 'library'
      - 'completion'
      - 'aliases'

- name: 'Set dotfiles facts.'
  ansible.builtin.set_fact:
    bash_ordered_segments: 'options path env library {{ bash_generic_items | join(" ") }} beets comics pi host completion aliases'

###############################################################################
# GENERIC & SPECIAL UNIVERSAL ITEMS
###############################################################################

- name: 'Copy Bash generic and special dotfiles to destination.'
  ansible.builtin.include: 'copy_bash_dotfiles.yaml'
  vars:
    id: "{{ dotfile_id }}"
    source: "{{ role_path }}/files/bash/{{ dotfile_id }}"
    dest: "{{ ansible_env.HOME }}/.bash.{{ dotfile_id }}.d"
  with_items: "{{ bash_generic_items + bash_special_items }}"
  loop_control:
    loop_var: 'dotfile_id'

###############################################################################
# ALIASES
###############################################################################

- name: 'Set Mac-Specific Aliases'
  block:

    - name: 'Create aliases for various BSD tools to the GNU equivalents.'
      ansible.builtin.copy:
        dest: "{{ ansible_env.HOME }}/.bash.aliases.d/{{ item }}.sh"
        content: |
          #!/usr/bin/env bash

          # Detect if we have a g{{ item }}.
          if [ -x "$(command -v g{{ item }})" ]; then
            alias {{ item }}="g{{ item }}";
          fi
      loop:
        - 'date'
        - 'du'
        - 'echo'
        - 'paste'
        - 'sed'
        - 'stat'
      changed_when: no


    - name: 'Create alias for md5sum.'
      ansible.builtin.copy:
        dest: "{{ ansible_env.HOME }}/.bash.aliases.d/md5sum.sh"
        content: |
          #!/usr/bin/env bash

          alias md5sum="md5";
      changed_when: no

  when: 'ndsc_host_is_mac'

###############################################################################
# HOST
###############################################################################

- name: 'Check for existence of Host dotfiles source.'
  ansible.builtin.stat:
    path: "{{ role_path }}/files/bash/host/{{ hostname }}"
  register: host_dotfiles_path

- name: 'Copy Bash Host-specific dotfiles to destination.'
  ansible.builtin.include: 'copy_bash_dotfiles.yaml'
  vars:
    id: 'host'
    source: "{{ role_path }}/files/bash/host/{{ hostname }}"
    dest: "{{ ansible_env.HOME }}/.bash.host.d"
  when: 'host_dotfiles_path.stat.exists'

###############################################################################
# RASPBERRY PI
###############################################################################

- name: 'Copy Bash Raspberry Pi dotfiles to destination.'
  ansible.builtin.include: 'copy_bash_dotfiles.yaml'
  vars:
    id: 'pi'
    source: "{{ role_path }}/files/bash/pi"
    dest: "{{ ansible_env.HOME }}/.bash.pi.d"
  when: 'ndsc_host_is_raspbian'

###############################################################################
# CORE
###############################################################################

- name: 'Copy Bash core dotfiles to destination.'
  ansible.builtin.template:
    backup: yes
    force: yes
    owner: "{{ ndsc_user }}"
    group: "{{ ndsc_group }}"
    mode: '0755'
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.{{ item | basename | regex_replace('^([^\\.]*).*', '\\1') }}"
  with_fileglob:
    - "{{ role_path }}/files/bash/core/*.sh.j2"
