---
- name: 'Install Apt packages.'
  ansible.builtin.apt:
    name:
      - 'curl'
      - 'git'
      - 'python3'
      - 'python3-pip'
      - 'rsync'
      - 'sudo'
    update_cache: yes
  when: 'host_uses_apt'

- name: 'Install Homebrew packages.'
  community.general.homebrew:
    name:
      - "jq"
      - "python@{{ software_versions.python }}"
      - "yq"
    update_homebrew: yes
  when: 'host_uses_homebrew'

- name: 'Install Pip packages.'
  ansible.builtin.pip:
    name:
      - 'ansible'
      - 'proxmoxer'
      - 'requests'
