---
- name: 'Install Apk packages.'
  become: yes
  ansible.builtin.apk:
    name:
      - 'bc'
      - 'curl'
      - 'git'
      - 'jq'
      - 'openssl-dev'
      - 'python3'
      - 'py3-pip'
      - 'rsync'
      - 'ssmtp'
    update_cache: yes
  when: 'host_uses_apk'

- name: 'Allow release-info to change for APT repositories.'
  become: yes
  ansible.builtin.command: 'apt-get update -y --allow-releaseinfo-change'
  args:
    warn: no
  when: 'host_uses_apt'

- name: 'Install Apt packages.'
  become: yes
  ansible.builtin.apt:
    name:
      - 'apt-file'
      - 'bc'
      - 'curl'
      - 'ffmpeg'
      - 'git'
      - 'jq'
      - 'libacl1-dev'
      - 'libssl-dev'
      - 'mailutils'
      - 'python3'
      - 'python3-pip'
      - 'python3-venv'
      - 'rsync'
    update_cache: yes
  when: 'host_uses_apt'

- name: 'Install Homebrew packages.'
  community.general.homebrew:
    name:
      - 'bat'
      - 'coreutils'
      - 'findutils'
      - 'ffmpeg'
      - 'fzf'
      - 'gawk'
      - 'gnu-indent'
      - 'gnu-sed'
      - 'gnutls'
      - 'grep'
      - 'gnu-tar'
      - 'jq'
      - 'parallel'
      - "python@{{ software_versions.python }}"
      - 'yq'
    update_homebrew: no
  when: 'host_uses_homebrew'

- name: 'Install Pip packages.'
  ansible.builtin.pip:
    name:
      - 'ansible'
      - 'awscli'
      - 'bdfr'
      - 'boto3'
      - 'proxmoxer'
      - 'requests'
      - 'torrent_parser'
      - 'virtualenv'
    virtualenv: "{{ dotfiles_home }}/.venv"
    virtualenv_site_packages: no

- name: 'Install non-Synology Pip packages.'
  ansible.builtin.pip:
    name:
      - 'borgbackup'
      - 'borgmatic'
  when: 'not host_is_synology'

