---
- name: 'Install Apk packages.'
  become: yes
  ansible.builtin.apk:
    name:
      - 'bc'
      - 'curl'
      - 'git'
      - 'jq'
      - 'python3'
      - 'py3-pip'
      - 'rsync'
      - 'ssmtp'
    update_cache: yes
  when: 'host_uses_apk'

- name: 'Install Apt packages.'
  become: yes
  ansible.builtin.apt:
    name:
      - 'bc'
      - 'curl'
      - 'ffmpeg'
      - 'git'
      - 'jq'
      - 'mailutils'
      - 'python3'
      - 'python3-pip'
      - 'rsync'
    update_cache: yes
  when: 'host_uses_apt'

- name: 'Install Homebrew packages.'
  community.general.homebrew:
    name:
      - 'awscli'
      - 'bat'
      - 'coreutils'
      - 'findutils'
      - 'ffmpeg'
      - 'fzf'
      - 'gawk'
      - 'gnu-indent'
      - 'gnu-sed'
      - 'gnutls'
      - 'grep'
      - 'gnu-tar'
      - 'jq'
      - 'parallel'
      - "python@{{ software_versions.python }}"
      - 'yq'
    update_homebrew: yes
  when: 'host_uses_homebrew'

- name: 'Install Pip packages.'
  ansible.builtin.pip:
    name:
      - 'ansible'
      - 'boto3'
      - 'proxmoxer'
      - 'torrent_parser'
      - 'requests'
