---
- name: 'Set common facts.'
  ansible.builtin.include: 'set_common_facts.yaml'

- name: 'Set user and group.'
  ansible.builtin.include: 'set_dotfiles_user.yaml'
  when: 'user is not defined or group is not defined'

- name: 'Create a normal user.'
  ansible.builtin.include: 'create_normal_user.yaml'
  when: 'user == "root"'

- name: 'Install some universally useful packages.'
  ansible.builtin.include: 'install_common_packages.yaml'

- name: 'Set dotfiles_home directory.'
  ansible.builtin.include: 'set_dotfiles_home_directory.yaml'
  when: 'dotfiles_home is not defined'

- name: 'Deploy Bash dotfiles.'
  ansible.builtin.include: 'deploy_bash_dotfiles.yaml'

- name: 'Deploy SSH dotfiles.'
  ansible.builtin.include: 'deploy_ssh_dotfiles.yaml'

- name: 'Deploy Git dotfiles.'
  ansible.builtin.include: 'deploy_git_dotfiles.yaml'

- name: 'Set the MOTD.'
  ansible.builtin.include: 'set_motd.yaml'

- name: 'Install the update cronjob.'
  ansible.builtin.cron:
    name: 'update-dotfiles'
    minute: '0'
    job: "/bin/bash -lc 'pushd \"{{ dotfiles_home }}/.dotfiles\" > /dev/null; ./update.sh > /dev/null;'"
