---

- name: 'Set user and group.'
  ansible.builtin.include: 'set_dotfiles_user.yaml'
  when: 'user is not defined or group is not defined'

- name: 'Set dotfiles_home directory.'
  ansible.builtin.include: 'set_dotfiles_home_directory.yaml'
  when: 'dotfiles_home is not defined'

#- name: 'Deploy Bash dotfiles.'
#  ansible.builtin.include: 'deploy_bash_dotfiles.yaml'

- name: 'Deploy SSH dotfiles.'
  ansible.builtin.include: 'deploy_ssh_dotfiles.yaml'

- name: 'Set the MOTD.'
  ansible.builtin.include: 'set_motd.yaml'
