---
- name: 'Perform some common tasks.'
  ansible.builtin.include_role:
    name: 'ndouglas.common'

- name: 'Deploy Bash dotfiles.'
  ansible.builtin.include: 'deploy_bash_dotfiles.yaml'

- name: 'Deploy SSH dotfiles.'
  ansible.builtin.include: 'deploy_ssh_dotfiles.yaml'

- name: 'Deploy Git dotfiles.'
  ansible.builtin.include: 'deploy_git_dotfiles.yaml'

- name: 'Deploy AWS dotfiles.'
  ansible.builtin.include: 'deploy_aws_dotfiles.yaml'

- name: 'Deploy Filebot dotfiles.'
  ansible.builtin.include: 'deploy_filebot_dotfiles.yaml'

- name: 'Deploy Reddit dotfiles.'
  ansible.builtin.include: 'deploy_reddit_dotfiles.yaml'

- name: 'Deploy TriggerHappy role.'
  ansible.builtin.include: 'deploy_triggerhappy_dotfiles.yaml'
  when: 'hostname == "bridges" and user != "root"'

- name: 'Set the MOTD.'
  ansible.builtin.include: 'set_motd.yaml'

- name: 'Check for existence of host-specific task.'
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/hosts/{{ inventory_hostname }}.yaml"
  register: 'host_task_path'

- name: 'Execute host-specific task.'
  ansible.builtin.include: "tasks/hosts/{{ inventory_hostname }}.yaml"
  when: 'host_task_path.stat.exists'

- name: 'Set the email address appropriately for cron jobs.'
  ansible.builtin.cron:
    name: MAILTO
    env: yes
    job: "{{ host_email_address }}"
  when: 'not host_is_synology'

- name: 'Install the update cronjob.'
  ansible.builtin.cron:
    name: 'update-dotfiles'
    minute: "{{ 60 | random(seed=user_at_hostname) }}"
    job: |
      /bin/bash -lc '~/.dotfiles/cron.sh;'
  when: 'not host_is_synology'
