---
- name: 'Set user and group.'
  ansible.builtin.include: 'set_dotfiles_user.yaml'
  when: 'user is not defined or group is not defined'

- name: 'Set common facts.'
  ansible.builtin.include: 'set_common_facts.yaml'

- name: 'Create a normal user.'
  ansible.builtin.include: 'create_normal_user.yaml'
  when: 'user == "root"'

- name: 'Enable Passwordless Sudo'
  become: yes
  ansible.builtin.copy:
    content: "{{ my.name.lower }} ALL=(ALL:ALL) NOPASSWD:ALL"
    dest: "/etc/sudoers.d/{{ my.name.lower }}"
    mode: 0440
  when: 'user != "root"'

- name: 'Install some universally useful packages.'
  ansible.builtin.include: 'install_common_packages.yaml'

- name: 'Set dotfiles_home directory.'
  ansible.builtin.include: 'set_dotfiles_home_directory.yaml'
  when: 'dotfiles_home is not defined'

- name: 'Deploy Bash dotfiles.'
  ansible.builtin.include: 'deploy_bash_dotfiles.yaml'

- name: 'Deploy SSH dotfiles.'
  ansible.builtin.include: 'deploy_ssh_dotfiles.yaml'

- name: 'Deploy Git dotfiles.'
  ansible.builtin.include: 'deploy_git_dotfiles.yaml'

- name: 'Deploy AWS dotfiles.'
  ansible.builtin.include: 'deploy_aws_dotfiles.yaml'

- name: 'Deploy Filebot dotfiles.'
  ansible.builtin.include: 'deploy_filebot_dotfiles.yaml'

- name: 'Deploy Reddit dotfiles.'
  ansible.builtin.include: 'deploy_reddit_dotfiles.yaml'

- name: 'Set the MOTD.'
  ansible.builtin.include: 'set_motd.yaml'

- name: 'Set the email address appropriately for cron jobs.'
  ansible.builtin.cron:
    name: MAILTO
    env: yes
    job: "{{ hostname }}@hellholt.net"

- name: 'Install the update cronjob.'
  ansible.builtin.cron:
    name: 'update-dotfiles'
    minute: "{{ 60 | random(seed=user_at_hostname) }}"
    job: |
      /bin/bash -lc '"{{ dotfiles_home }}"/.dotfiles/cron.sh;'
