---
- name: 'Set the MOTD.'
  ansible.builtin.get_url:
    url: "{{ motd_base_url }}/{{ hostname }}.txt"
    dest: '/etc/motd'
    force: no
    owner: 'root'
    mode: '0644'
  become: yes
  ignore_errors: yes
