---
- name: 'Detect when we are running Synology DSM.'
  stat:
    path: /etc/synoinfo.conf
  register: synology_info_file
  when: '(ansible_distribution == "OtherLinux")'

- name: 'Detect when we are running Proxmox.'
  stat:
    path: /etc/pve
  register: proxmox_pve_directory
  when: '(ansible_distribution == "Debian")'

- name: 'Set more facts.'
  ansible.builtin.set_fact:
    host_uses_apt: "{{ ansible_distribution == 'Debian' }}"
    host_uses_homebrew: "{{ ansible_distribution == 'MacOSX' }}"
    host_is_raspbian: "{{ ansible_distribution == 'Debian' and ansible_lsb.has_key('id') and ansible_lsb.id == 'Raspbian' }}"
    host_is_debian: "{{ ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' }}"
    host_is_mac: "{{ ansible_distribution == 'MacOSX' }}"
    host_is_proxmox: "{{ ansible_distribution == 'Debian' and proxmox_pve_directory.stat.exists }}"
    host_is_synology: "{{ ansible_distribution == 'OtherLinux' and synology_info_file.stat.exists }}"
    dotfiles_source: "{{ playbook_dir | dirname | dirname }}/dotfiles"
