- name: 'Enable IPv4 forwarding.'
  become: yes
  ansible.builtin.sysctl:
    name: 'net.ipv4.ip_forward'
    value: '1'
    state: 'present'
    reload: yes
    sysctl_set: yes
    sysctl_file: '/etc/sysctl.conf'

- name: 'Unblock port 53.'
  ansible.builtin.lineinfile:
    path: '/etc/systemd/resolved.conf'
    regexp: '^#?DNSStubListener=yes'
    line: 'DNSStubListener=no'
  register: 'resolved_conf'

- name: 'Restart resolved.'
  ansible.builtin.service:
    name: 'systemd-resolved'
    state: 'restarted'
  when: 'resolved_conf.changed'

- name: 'Pi-Hole directories.'
  become: yes
  file:
    path: "{{ item }}"
    state: 'directory'
  loop:
    - '/opt/pihole/etc'
    - '/opt/pihole/dnsmasq.d'

- name: 'Remove existing Pi-Hole (if any).'
  become: yes
  ansible.builtin.docker_container:
    name: 'pihole'
    state: 'absent'

- name: 'Pi-Hole setup.'
  become: yes
  ansible.builtin.docker_container:
    name: 'pihole'
    env:
      DNS1: "{{ pihole_dns1 | default('208.67.222.222') }}"
      DNS2: "{{ pihole_dns2 | default('208.67.220.220') }}"
      WEBPASSWORD: "{{ pihole_password | default(password) }}"
    image: 'pihole/pihole:latest'
    network_mode: 'host'
    volumes:
      - '/opt/pihole/etc:/etc/pihole/:rw'
      - '/opt/pihole/dnsmasq.d:/etc/dnsmasq.d:rw'
    pull: yes
    restart_policy: 'always'
    container_default_behavior: 'no_defaults'
  no_log: no
