---
- name: 'Set some important facts...'
  ansible.builtin.set_fact:
    ansible_connection: 'ssh'
    ansible_ssh_user: 'root'

- name: 'Install Apt packages.'
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: yes
  loop:
    - 'curl'
    - 'git'
    - 'python3'
    - 'python3-pip'
    - 'rsync'
    - 'sudo'

- name: 'Install Pip packages.'
  ansible.builtin.pip:
    name: "{{ item }}"
  loop:
    - 'ansible'
    - 'proxmoxer'
    - 'requests'

- name: 'Enable kernel modules.'
  ansible.builtin.copy:
    content: "{{ item }}"
    dest: "/etc/modules-load.d/{{ item }}.conf"
  loop:
    - 'aufs'
    - 'br_netfilter'
    - 'overlay'

- name: 'Modprobe kernel modules.'
  community.general.modprobe:
    name: "{{ item }}"
  loop:
    - 'aufs'
    - 'br_netfilter'
    - 'overlay'
