---
- name: 'Gather host facts.'
  ansible.builtin.include: 'set_pve_host_facts.yaml'

- name: 'Display information about the container.'
  ansible.builtin.debug:
    var: 'hostvars[inventory_hostname]'
