- name: 'Gather facts about this host.'
  remote_user: 'root'
  ansible.builtin.setup:

- name: 'Install dotfiles.'
  remote_user: 'root'
  block:

  - name: 'Install common packages.'
    ansible.builtin.include_role:
      name: 'ndouglas.deploy_dotfiles'
      tasks_from: 'install_common_packages.yaml'

  - name: 'Install dotfiles (as root).'
    ansible.builtin.include_role:
      name: 'ndouglas.host_role.dotfiles'

- name: 'Install dotfiles (as normal user).'
  ansible.builtin.include_role:
    name: 'ndouglas.host_role.dotfiles'
  vars:
    ansible_ssh_pass: "{{ password }}"
