- name: 'Gather facts about this host.'
  ansible.builtin.setup:
  remote_user: 'root'

- name: 'Install dotfiles.'
  remote_user: 'root'
  ansible.builtin.include_role:
    name: 'ndouglas.host_role.dotfiles'

- name: 'Install dotfiles as normal user.'
  ansible.builtin.include_role:
    name: 'ndouglas.host_role.dotfiles'
  vars:
    ansible_ssh_pass: "{{ password }}"

- name: 'Gather facts about this host.'
  ansible.builtin.setup:

- name: 'Set user and group.'
  ansible.builtin.include_role:
    name: 'ndouglas.deploy_dotfiles'
    tasks_from: 'set_dotfiles_user.yaml'
  when: 'user is not defined or group is not defined'

- name: 'Run host-specific setup (if applicable).'
  block:

  - name: 'Check for existence of host-specific task.'
    delegate_to: 'localhost'
    ansible.builtin.stat:
      path: "{{ role_path }}/tasks/hosts/{{ inventory_hostname }}.yaml"
    register: host_task_path

  - name: 'Set common facts.'
    ansible.builtin.include_role:
      name: 'ndouglas.deploy_dotfiles'
      tasks_from: 'set_common_facts.yaml'
    when: 'host_task_path.stat.exists'

  - name: 'Execute host-specific task.'
    ansible.builtin.include: "tasks/hosts/{{ inventory_hostname }}.yaml"
    when: 'host_task_path.stat.exists'
