---
- name: 'Gather host facts.'
  ansible.builtin.include_role:
    name: 'ndouglas.proxmox_host'
    tasks_from: 'set_pve_host_facts.yaml'

- name: 'Switch back to a normal connection method.'
  ansible.builtin.set_fact:
    ansible_connection: 'ssh'

- name: 'Set up cluster (but only on master).'
  remote_user: 'root'
  when: 'k8s_role == "master"'
  block:

    - name: 'Check for existence of cluster-specific task.'
      delegate_to: 'localhost'
      ansible.builtin.stat:
        path: "{{ role_path }}/tasks/clusters/{{ k8s_cluster }}.yaml"
      register: 'cluster_task_path'

    - name: 'Gather host facts.'
      ansible.builtin.setup:

    - name: 'Set user and group.'
      ansible.builtin.include_role:
        name: 'ndouglas.deploy_dotfiles'
        tasks_from: 'set_dotfiles_user.yaml'
      when: 'user is not defined or group is not defined'

    - name: 'Set common facts.'
      ansible.builtin.include_role:
        name: 'ndouglas.deploy_dotfiles'
        tasks_from: 'set_common_facts.yaml'

    - name: 'Execute cluster-specific task.'
      ansible.builtin.include: "tasks/clusters/{{ k8s_cluster }}.yaml"
      when: 'cluster_task_path.stat.exists'
