---

- name: 'Deploy Dotfiles'
  hosts: 'localhost'
  vars:
    ansible_connection: local
  tasks:

    - name: 'Deploy dotfiles.'
      ansible.builtin.include_role:
        name: 'ndouglas.deploy_dotfiles'
