---
- name: "Create privately-resolvable DNS records for the host '{{ ansible_hostname }}'."
  delegate_to: localhost
  community.aws.route53:
    overwrite: yes
    aws_access_key: "{{ route53.access_key }}"
    aws_secret_key: "{{ route53.secret_key }}"
    hosted_zone_id: "{{ route53.zone_ids.private }}"
    state: 'present'
    type: 'A'
    record: "{{ fqdns.private }}"
    value: "{{ ipv4_address }}"

- name: "Create privately-resolvable wildcard DNS records for the host '{{ ansible_hostname }}'."
  delegate_to: localhost
  community.aws.route53:
    alias: yes
    alias_hosted_zone_id: "{{ route53.zone_ids.private }}"
    overwrite: yes
    aws_access_key: "{{ route53.access_key }}"
    aws_secret_key: "{{ route53.secret_key }}"
    hosted_zone_id: "{{ route53.zone_ids.private }}"
    state: 'present'
    type: 'A'
    record: "*.{{ fqdns.private }}"
    value: "{{ fqdns.private }}"

- name: "Create publicly-resolvable DNS records for the host '{{ ansible_hostname }}'."
  delegate_to: localhost
  community.aws.route53:
    alias: yes
    alias_hosted_zone_id: "{{ route53.zone_ids.personal }}"
    overwrite: yes
    aws_access_key: "{{ route53.access_key }}"
    aws_secret_key: "{{ route53.secret_key }}"
    hosted_zone_id: "{{ route53.zone_ids.personal }}"
    state: 'present'
    type: 'A'
    record: "{{ fqdns.personal }}"
    value: "{{ domains.personal }}"

- name: "Create publicly-resolvable wildcard DNS records for the host '{{ ansible_hostname }}'."
  delegate_to: localhost
  community.aws.route53:
    alias: yes
    alias_hosted_zone_id: "{{ route53.zone_ids.personal }}"
    overwrite: yes
    aws_access_key: "{{ route53.access_key }}"
    aws_secret_key: "{{ route53.secret_key }}"
    hosted_zone_id: "{{ route53.zone_ids.personal }}"
    state: 'present'
    type: 'A'
    record: "*.{{ fqdns.personal }}"
    value: "{{ fqdns.personal }}"
