# This should always be 'python3' because it's 2021.
ansible_python_interpreter: 'python3'

# My domains that I use for stupid things.
domains:
  personal: 'bitterbridge.net'
  public: 'darkdell.net'
  private: 'hellholt.net'

# Calculated FQDNs for the current hostname.
fqdns:
  personal: "{{ ansible_hostname }}.{{ domains.personal }}"
  public: "{{ ansible_hostname }}.{{ domains.public }}"
  private: "{{ ansible_hostname }}.{{ domains.private }}"

# Calculated IPv4 address.  Doesn't always work, usually does.
ipv4_address: "{{ ansible_default_ipv4.address | default(ansible_all_ipv4_addresses[0]) }}"

vault_password_file: '~/.ansible_vault_password'
