# This should always be 'python3' because it's 2021.
ansible_python_interpreter: 'python3'

# My domains that I use for stupid things.
domains:
  personal: 'bitterbridge.net'
  public: 'darkdell.net'
  private: 'hellholt.net'

# Lowercase hostname.
hostname: "{{ ansible_hostname | lower }}"

# Calculated FQDNs for the current hostname.
fqdns:
  personal: "{{ hostname }}.{{ domains.personal }}"
  public: "{{ hostname }}.{{ domains.public }}"
  private: "{{ hostname }}.{{ domains.private }}"

# Calculated IPv4 address.  Doesn't always work, usually does.
ipv4_address: "{{ ansible_default_ipv4.address | default(ansible_all_ipv4_addresses[0]) }}"

vault_password_file: "{{ ansible_env.HOME }}/.dotfiles_vault_password"

my:
  name:
    short: 'Nathan'
    lower: 'nathan'
    full: 'Nathan Douglas'
  email:
    github: 'github@tenesm.us'

# My Gitconfig.
gitconfig:
  core.editor: 'nano'
  user.name: "{{ my.name.full }}"
  user.email: "{{ my.email.github }}"
  pull.rebase: 'true'

software_versions:
  python: '3.9'

# Structures Stored in the Vault

# Password
#
# password: 'some-string'

# GitHub Access Token
#
# github_access_token: 'some-string'

# AWS
#
# aws:
#   defaults:
#     region: 'us-east-1'
#     output: 'json'
#   profiles:
#     route53:
#       key_id: 'some-access-key-id'
#       secret_key: 'some-secret-key'
#       zone_ids:
#         personal: 'personal-domain-zone-id'
#         public: 'public-domain-zone-id'
#         private: 'private-domain-zone-id'

# Filebot
#
# filebot:
#   license: 'filebot-license-string'

# Podcasts
#
# podcasts:
#   feeds:
#     - 'some-feed'

# Reddit
#
# reddit:
#   subreddits:
#     - 'some-subreddit-name'

# YouTube
#
# youtube:
#   channels:
#     - 'some-channel-name'
#   playlists:
#     - 'some-playlist-name'
#   users:
#     - 'some-user-name'
#
