# This should always be 'python3' because it's 2021.
ansible_python_interpreter: 'python3'

# My domains that I use for stupid things.
domains:
  personal: 'bitterbridge.net'
  public: 'darkdell.net'
  private: 'hellholt.net'

# Calculated IPv4 address.  Doesn't always work, usually does.
ipv4_address: "{{ ansible_default_ipv4.address | default(ansible_all_ipv4_addresses[0]) }}"

vault_password_file: "{{ ansible_env.HOME }}/.dotfiles_vault_password"

my:
  name:
    short: 'Nathan'
    lower: 'nathan'
    full: 'Nathan Douglas'
  email:
    github: 'github@tenesm.us'
  local:
    timezone: 'America/New_York'
  domains:
    personal: 'bitterbridge.net'
    public: 'darkdell.net'
    private: 'hellholt.net'

# Lowercase hostname.
hostname: "{{ ansible_hostname | lower }}"

# Calculated FQDNs for the current hostname.
fqdns:
  personal: "{{ hostname }}.{{ my.domains.personal }}"
  public: "{{ hostname }}.{{ my.domains.public }}"
  private: "{{ hostname }}.{{ my.domains.private }}"

# My Gitconfig.
gitconfig:
  core.editor: 'nano'
  user.name: "{{ my.name.full }}"
  user.email: "{{ my.email.github }}"
  pull.rebase: 'true'

motd_base_url: "https://raw.githubusercontent.com/ndouglas/asoiaf-noble-house-images/master/utf8/40"

prompt:
  emoji: ''
  colors:
    primary: 188
    secondary: 159
    tertiary: 102
pve_mounts: []

# Structures Stored in the Vault

# Password
#
# password: 'some-string'

# GitHub Access Token
#
# github_access_token: 'some-string'

# AWS
#
# aws:
#   defaults:
#     region: 'us-east-1'
#     output: 'json'
#   profiles:
#     route53:
#       key_id: 'some-access-key-id'
#       secret_key: 'some-secret-key'
#       zone_ids:
#         personal: 'personal-domain-zone-id'
#         public: 'public-domain-zone-id'
#         private: 'private-domain-zone-id'

# Filebot
#
# filebot:
#   license: 'filebot-license-string'

# Home Assistant
#
# home_assistant:
#   access_key: 'some-string'

# Podcasts
#
# podcasts:
#   feeds:
#     - 'some-feed'

# Proxmox
#
# proxmox:
#   pve_api_username: 'some-string'
#   pve_api_password: 'some-string'

# Reddit
#
# reddit:
#   subreddits:
#     - 'some-subreddit-name'

# Torrents
#
# torrents:
#   announce_map:
#     some-domain-name: "some-replacement-domain-name"

# YouTube
#
# youtube:
#   channels:
#     - 'some-channel-name'
#   playlists:
#     - 'some-playlist-name'
#   users:
#     - 'some-user-name'
#

# ndouglas.setup_common
ndsc_set_hostname: yes
ndsc_enable_passwordless_sudo: yes
ndsc_create_normal_user: yes
ndsc_install_common_packages: no
ndsc_reinstall_pip: no
ndsc_normal_user_name: "{{ my.name.lower }}"
ndsc_local_timezone: "{{ my.local.timezone }}"
ndsc_host_email_domain: "{{ my.domains.private }}"
ndsc_hostname: "{{ hostname }}"

# ndouglas.setup_host
ndsh_setup_common: no
ndsh_normal_user_name: "{{ my.name.lower }}"
ndsh_host_email_domain: "{{ my.domains.private }}"
ndsh_local_timezone: "{{ my.local.timezone }}"
ndsh_hostname: "{{ hostname }}"
ndsh_aws_account_id: "{{ aws.defaults.account_id }}"
ndsh_aws_master_access_key: "{{ aws.profiles.master.key_id }}"
ndsh_aws_master_secret_key: "{{ aws.profiles.master.secret_key }}"
ndsh_aws_iam_host_user: "{{ my.domains.private }}_hosts_{{ ndsh_hostname }}"
ndsh_aws_iam_host_password: "{{ password }}"
ndsh_aws_region: 'us-east-1'
ndsh_aws_ssm_policy_pattern: "{{ my.domains.private }}.hosts.{{ ndsh_hostname }}.*"
ndsh_docker_hub_login: yes
ndsh_docker_hub_username: "{{ docker.hub.username }}"
ndsh_docker_hub_password: "{{ docker.hub.password }}"
ndsh_route53_private_zone_id: "{{ aws.profiles.route53.zone_ids.private }}"
ndsh_route53_personal_zone_id: "{{ aws.profiles.route53.zone_ids.personal }}"
ndsh_route53_private_domain_name: "{{ my.domains.private }}"
ndsh_route53_personal_domain_name: "{{ my.domains.personal }}"
ndsh_key_ip_address: 'pve_ip_address'
ndsh_borg_username: "{{ ndsh_normal_user_name }}"
ndsh_borg_server: 'uller'
ndsh_borg_repo_path: '/volume1/Borg'
ndsh_borg_source_directories: []
ndsh_borg_passphrase: "{{ password }}"
ndsh_k8s_nfs_prefix: '/leo/nfs/k8s_clusters'
ndsh_nfs_mount_options: 'rw,async,no_subtree_check,no_wdelay,crossmnt,insecure,no_root_squash,insecure_locks,sec=sys'
ndsh_local_share_prefix: '/leo/local/hosts'
ndsh_local_share_hostnames: "{{ groups[pve_cluster_id] }}"
ndsh_nfs_hostnames: "{{ groups['pve_hosts'] }}"
ndsh_node_nfs_prefix: '/leo/nfs/hosts'
ndsh_pihole_dns1: '208.67.222.222'
ndsh_pihole_dns2: '208.67.220.220'
ndsh_pihole_password: null
ndsh_host_roles:
  - 'aws_iam_user'
  - 'aws_ssm_policy'
  - 'route53'
#   - 'dotfiles_root'
#   - 'dotfiles'

# ndouglas.proxmox
ndpve_node: "{{ pve_node }}"
ndpve_api_username: "{{ proxmox.pve_api_username }}"
ndpve_api_password: "{{ proxmox.pve_api_password }}"
ndpve_template: "{{ pve_ostemplate | default('ubuntu-21.04-standard_21.04-1_amd64.tar.gz') }}"
ndpve_node_mountpoints: "{{ pve_mounts | default([]) }}"
ndpve_vm_id: "{{ pve_vm_id }}"
ndpve_hostname: "{{ inventory_hostname | lower }}"
ndpve_root_password: "{{ password }}"
ndpve_ssh_pub_key: "{{ proxmox.pve_ssh_pub_key }}"
ndpve_cores: "{{ pve_cores | default(4) }}"
ndpve_memory_size: "{{ pve_memory_size | default(16384) }}"
ndpve_swap_size: "{{ pve_swap_size | default(0) }}"
ndpve_onboot: "{{ pve_onboot | default(yes) }}"
ndpve_unprivileged: "{{ pve_unprivileged | default(no) }}"
ndpve_rootfs_size: "{{ pve_rootfs_size | default(16) }}"
ndpve_features: "{{ pve_features | default('mount=nfs,keyctl=1,nesting=1') }}"

# ndouglas.kubernetes
ndk8s_nfs_server_ip_address: '10.3.0.2'
ndk8s_argocd_password: "{{ password }}"
ndk8s_aws_iam_cluster_user: "ndk8s_{{ k8s_cluster }}"
ndk8s_aws_iam_cluster_password: "{{ lookup('password', '/dev/null length=12 chars=ascii_letters,digits,punctuation') }}"
ndk8s_aws_ssm_policy_pattern: "{{ my.domains.private }}.clusters.{{ k8s_cluster }}.*"
