---
- name: 'Set some important facts...'
  ansible.builtin.set_fact:
    ansible_connection: 'ssh'
    ansible_ssh_user: 'root'

- name: 'Install Apt packages.'
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: yes
  loop:
    - 'curl'
    - 'git'
    - 'python3'
    - 'python3-pip'
    - 'rsync'
    - 'sudo'

- name: 'Install Pip packages.'
  ansible.builtin.pip:
    name: "{{ item }}"
  loop:
    - 'ansible'
    - 'proxmoxer'
    - 'requests'

- name: 'Enable kernel modules.'
  ansible.builtin.copy:
    content: "{{ item }}"
    dest: "/etc/modules-load.d/{{ item }}.conf"
  loop:
    - 'aufs'
    - 'br_netfilter'
    - 'overlay'

- name: 'Modify some settings to prepare for Kubernetes.'
  ansible.builtin.copy:
    dest: '/etc/sysctl.d/kubernetes.conf'
    content: |
      vm.swappiness=0
      net.ipv4.ip_forward=1

- name: 'Run all sysctl updates.'
  ansible.builtin.shell:
    cmd: 'sysctl --system'

- name: 'Disable swap if not already disabled.'
  ansible.builtin.shell:
    cmd: 'swapoff -a'

- name: 'Modprobe kernel modules.'
  community.general.modprobe:
    name: "{{ item }}"
  loop:
    - 'aufs'
    - 'br_netfilter'
    - 'overlay'
