---
- name: 'Gather host facts.'
  ansible.builtin.include: 'set_host_facts.yaml'

- name: 'Stop and remove the container.'
  delegate_to: "{{ pve_node }}"
  block:

  - name: 'Stop the container.'
    community.general.proxmox:
      vmid: "{{ pve_vm_id }}"
      api_user: "{{ proxmox.pve_api_username }}"
      api_password: "{{ proxmox.pve_api_password }}"
      api_host: "{{ pve_node }}"
      state: 'stopped'
      force: yes
      proxmox_default_behavior: 'no_defaults'
    ignore_errors: yes

  - name: 'Remove the container.'
    community.general.proxmox:
      vmid: "{{ pve_vm_id }}"
      api_user: "{{ proxmox.pve_api_username }}"
      api_password: "{{ proxmox.pve_api_password }}"
      api_host: "{{ pve_node }}"
      state: 'absent'
      force: yes
      proxmox_default_behavior: 'no_defaults'
