---
- name: 'Copy Bash Comics dotfiles to destination.'
  ansible.builtin.include: "{{ role_path }}/tasks/copy_bash_dotfiles.yaml"
  vars:
    id: 'comics'
    source: "{{ role_path }}/files/bash/comics"
    dest: "{{ ansible_env.HOME }}/.bash.comics.d"

- name: 'Syno-CLI Path Components'
  ansible.builtin.copy:
    dest: "{{ ansible_env.HOME }}/.bash.path.d/syno-cli.sh"
    content: |
     #!/usr/bin/env bash

      # Syno-CLI provides nano, tput, etc.
      if [ -d "/volume1/@appstore/synocli-file/bin" ]; then
        PATH="${PATH}:/volume1/@appstore/synocli-file/bin";
      fi
