---
- name: 'Create sudo group.'
  ansible.builtin.group:
    name: 'sudo'
    state: 'present'

- name: 'Create normal user account.'
  ansible.builtin.user:
    name: "{{ normal_user_name }}"
    password: "{{ password | password_hash('sha512', hostname) }}"
    shell: '/bin/bash'
    append: yes
    groups: 'sudo'
    create_home: yes
