---
- name: 'Allow release-info to change for APT repositories.'
  become: yes
  ansible.builtin.command: 'apt-get update -y --allow-releaseinfo-change'
  args:
    warn: no
  when: 'host_uses_apt'
  changed_when: no

- name: 'Install Apt packages.'
  become: yes
  ansible.builtin.apt:
    name:
      - 'apt-file'
      - 'bc'
      - 'build-essential'
      - 'cargo'
      - 'curl'
      - 'ffmpeg'
      - 'git'
      - 'jq'
      - 'libacl1-dev'
      - 'libffi-dev'
      - 'libssl-dev'
      - 'mailutils'
      - 'python3'
      - 'python3-apt'
      - 'python3-dev'
      - 'python3-pip'
      - 'python3-setuptools'
      - 'python3-venv'
      - 'rsync'
      - 'sshpass'
      - 'sudo'
    update_cache: yes
  when: 'host_uses_apt'

- name: 'Install Homebrew packages.'
  community.general.homebrew:
    name:
      - 'argocd'
      - 'bat'
      - 'coreutils'
      - 'findutils'
      - 'ffmpeg'
      - 'fzf'
      - 'gawk'
      - 'gnu-indent'
      - 'gnu-sed'
      - 'gnutls'
      - 'grep'
      - 'gnu-tar'
      - 'jq'
      - 'parallel'
      - "python@{{ software_versions.python }}"
      - 'sshpass'
      - 'yq'
    update_homebrew: no
  when: 'host_uses_homebrew'

- name: 'Make sure pip is at the latest version.'
  become: yes
  ansible.builtin.pip:
    name: 'pip'
    state: 'forcereinstall'
  changed_when: no

- name: 'Install Pip packages.'
  become: yes
  ansible.builtin.pip:
    name:
      - 'ansible'
      - 'awscli'
      - 'bdfr'
      - 'boto3'
      - 'kubernetes'
      - 'proxmoxer'
      - 'requests'
      - 'torrent_parser'
      - 'virtualenv'
    extra_args: '--ignore-installed'

- name: 'Install non-Synology Pip packages.'
  ansible.builtin.pip:
    name:
      - 'borgbackup'
      - 'borgmatic'
  when: 'not host_is_synology'

- name: 'Set a fact to indicate that we have installed these packages.'
  ansible.builtin.set_fact:
    common_packages_installed: yes
