pve_cores: 4
pve_memory_size: 16384
pve_rootfs_size: 32
ndsh_host_roles: "{{ ndsh_host_roles + [
  'route53'.
  'docker',
  'k8s',
  ] }}"
k8s_cluster_roles:
  - 'route53'                     # Add DNS records.
  - 'get_config'                  # Get Kubectl config.
  - 'helm'                        # Install Helm for package control.
  - 'metrics_server'              # Local metrics gathering and reporting.
  - 'nfs_provisioner'             # Allow provisioning persistent network storage.
  - 'local_storage_provisioner'   # Allow provisioning persistent local storage.
  - 'cert_manager'                # Permit TLS cert generation.
  - 'traefik'                     # Install and setup Traefik as Ingress Controller.
  - 'argocd'                      # Install ArgoCD as GitOps controller.
  - 'whoami'                      # Install Whoami as test service.
  - 'aws_ssm_policy'              # Allow retrieval of secrets from AWS SSM Parameter Store.
  - 'external_secrets'            # Allow secrets to persist past cluster lifetimes.
